### PR TITLE
Use exported fcns from perl core if available

### PR DESCRIPTION
**Pull request by khwilliamson**
You may want to drop the first one; I don't know where those changes came from nor what they should be.

### CODE REVIEW

**Comment by khwilliamson** [comment]
I forgot to mention, you can run this against
https://perl5.git.perl.org/perl.git/shortlog/refs/heads/smoke-me/khw-BHooks
to see what happens with a perl that exports the functions

**Comment by karenetheridge** [comment]
re 7a789db:

>  I don't know where these changes came from
> These appear to have changed from what I downloaded from cpan, but I
> didn't do it.

looking at the history, I see commit 66a934c021, which are suggestions applied after running `perl ppport.h --compat-version=5.006 --quiet *.h Parser.xs stolen_chunk_of_toke.c`. Were they not sensible changes?

**Comment by karenetheridge** [comment]
When I run ppport.h (either version 3.44 or 3.45, the latest) on this code, it suggests making the following changes:

```
--- Parser.xs
+++ Parser.xs.patched
@@ -10,7 +10,7 @@
 #include "perl.h"
 #include "XSUB.h"
 
-#define NEED_PL_parser
+#define NEED_PL_parser_GLOBAL
 #include "ppport.h"
 
 #include "hook_parser.h"
--- stolen_chunk_of_toke.c
+++ stolen_chunk_of_toke.c.patched
@@ -19,7 +19,7 @@
 
 #include "EXTERN.h"
 #include "perl.h"
-#define NEED_PL_parser
+#define NEED_sv_2pv_flags
 #include "ppport.h"
 
 /* the following #defines are stolen from assorted headers, not toke.c (mst) */
@@ -129,7 +129,7 @@
 /* Invoke the idxth filter function for the current rsfp.       */
 /* maxlen 0 = read one text line */
 I32
-Perl_filter_read(pTHX_ int idx, SV *buf_sv, int maxlen)
+filter_read(pTHX_ int idx, SV *buf_sv, int maxlen)
 {
     filter_t funcp;
     SV *datasv = NULL;

```

**Comment by karenetheridge** [comment]
Can we include a reference to the perl RT# and blead commits where relevant changes were made? I'm having trouble tracking down what changes in blead this ties to.  If they are in 5.29.9, they don't seem to be taking effect, as I still see compiler warnings (e.g. `'Perl_is_utf8_mark' is deprecated`) indicating that stolen_chunk_of_toke.c is still being included.

**Comment by khwilliamson** [comment]
On 4/13/19 9:09 PM, Karen Etheridge wrote:
> re 7a789db 
> <https://github.com/karenetheridge/B-Hooks-Parser/commit/7a789db5b2bfc4eb9ddbac0d23bb9f2bbca3c993>:
> 
>     I don't know where these changes came from
>     These appear to have changed from what I downloaded from cpan, but I
>     didn't do it.
> 
> looking at the history, I see commit 66a934c 
> <https://github.com/karenetheridge/B-Hooks-Parser/commit/66a934c02168048cebeb5a95d6ad3bbbe6e8f707>, 
> which are suggestions applied after running |perl ppport.h 
> --compat-version=5.006 --quiet *.h Parser.xs stolen_chunk_of_toke.c|. 
> Were they not sensible changes?
> 

I don't know.  I merely noticed a discrepancy with what I was expecting. 
  I no longer remember how I got things.  My guess is I forked the 
repository, made my changes, pushed those back to my fork,, then issued 
a PR.  And these discrepancies showed up.  They look reasonable to me, 
but I wanted to point out they existed, and I'm unsure of them.

**Comment by khwilliamson** [comment]
On 4/13/19 9:17 PM, Karen Etheridge wrote:
> Can we include a reference to the perl RT# and blead commits where 
> relevant changes were made? I'm having trouble tracking down what 
> changes in blead this ties to. If they are in 5.29.9, they don't seem to 
> be taking effect, as I still see compiler warnings (e.g. 
> |'Perl_is_utf8_mark' is deprecated|) indicating that 
> stolen_chunk_of_toke.c is still being included.

The ticket is [perl #133318] BBC: blead breaks B::Hooks::Parser​

Blead isn't fixed until today, aabfeadc64376a5e473fe2a3fed20fd0d311dca5

But I thought I had given you a link to a smoke-me workspace that had 
the changes in it, so you could test it, if you wished, against that. 
Eventually, I pushed them to blead.

So if you're running against any blead earlier than a couple hours ago, 
you will get that result, but the code should pass its tests. 
Afterwards, you shouldn't get that warning, and the code should pass its 
tests.

**Comment by karenetheridge** [comment]
> Blead isn't fixed until today, aabfeadc64376a5e473fe2a3fed20fd0d311dca5

Ok, splendid! I had assumed they were already in so I got confused.

> so you could test it, if you wished, against that

I didn't look at this PR until today; sorry about that! bad timing on my part.

**Comment by karenetheridge** [comment]
Compiling your changes against tonight's blead works, with no compiler warnings!  I have pushed up the commits and travis is chewing on it now. many thanks!

**Comment by karenetheridge** [comment]
https://travis-ci.org/karenetheridge/B-Hooks-Parser/builds/519845533

**Pull request closed without merging**
